apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: monitoring
spec:
  interval: 15m0s
  chart:
    spec:
      chart: fluent-bit
      version: "2.6.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    serviceMonitor:
      enabled: true
    loki:
      serviceName: loki-gateway
      servicePort: 80
      servicePath: /loki/api/v1/push
    config:
      loglevel: info
      memBufLimit: 50MB
      labels: '{job="fluent-bit",cluster="week9-1"}'
      labelMap:
        kubernetes:
          namespace_name: namespace
          pod_name: pod
          container_name: container
          host: node
        stream: stream
