apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 15m0s
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "69.8.2"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    crds:
      enabled: true
    alertmanager:
      enabled: false
    prometheusOperator:
      enabled: true
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeControllerManager:
      enabled: false
    grafana:
      enabled: true
      defaultDashboardsEnabled: true
      adminPassword: admin
      service:
        type: LoadBalancer
      grafana.ini:
        users:
          viewers_can_edit: true
        auth.anonymous:
          enabled: true
          org_role: Viewer
      additionalDataSources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki-gateway.monitoring.svc.cluster.local
          isDefault: false
          uid: loki
          jsonData:
            derivedFields:
              - name: TraceID
                matcherRegex: 'trace_id":"([a-f0-9]+)"'
                datasourceUid: tempo
                url: '$${__value.raw}'
        - name: Tempo
          type: tempo
          access: proxy
          url: http://tempo.monitoring.svc.cluster.local:3100
          uid: tempo
          jsonData:
            tracesToLogsV2:
              datasourceUid: loki
            serviceMap:
              datasourceUid: prometheus
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          isDefault: true
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        retention: 7d
        enableRemoteWriteReceiver: true
    nodeExporter:
      enabled: true
    kubeStateMetrics:
      enabled: true
